### ISSUE TITLE
Change 'port' to 'host' in install-idp

### ISSUE THREAD

**Issue by tomzeller** [iay/shibboleth-idp-docker#11]
Typo. s/port/host. The following :

 echo jetty.nonhttps.port=localhost>>$M

should be

 echo jetty.nonhttps.host=localhost>>$M

in install-idp

**Comment by iay** [comment]
That whole section was removed in late 2018 to avoid disturbing an existing Jetty install. More recently, I've moved the whole Jetty business out of the IdP install and into the container image.

I reckon this issue is now moot, so closing.
