### ISSUE TITLE
running install got permission denied

### ISSUE THREAD

**Issue by tahder** [iay/shibboleth-idp-docker#20]
I'm stuck when I issue ./install
/bin/bash: /data/install-idp: Permission denied

I even changed the permission but seems nothing helps or even add on the Dockerfile` RUN ["chmod", "+x", "/data/install-idp"]`

Hope can give insight into what caused it.

**Comment by tahder** [comment]
disregard this - lately notice that I'm using the podman and it has been an alias to docker, which causing the issue. I reinstall it using the docker from it's repository.

**Comment by iay** [comment]
Glad you got things sorted. I don't use `podman` here so I don't really have much insight into ways in which it is different.
