### ISSUE TITLE
Update property-driven installation for IdP V5

### ISSUE THREAD

**Issue by tomzeller** [iay/shibboleth-idp-docker#21]
Looks like property-driven installation of the IdP needs to be updated for IdP V5.

https://github.com/iay/shibboleth-idp-docker/blob/81d7c275d03d2e5d731b6ece001164ce399ffa14/install-idp#L45

https://shibboleth.atlassian.net/wiki/spaces/IDP5/pages/3199500577/Installation#Command-line-options

**Comment by reyniel26** [comment]
Its now updated 
https://github.com/iay/shibboleth-idp-docker/blob/f4cf4460f3357c0a77d58e1195db1e8bc1c5ec20/install-idp#L55

**Comment by iay** [comment]
I believe you're correct; I did rework that section to make it compliant with v5 as there were quite a lot of changes to the installer this time round.

Thanks. Closing.
