### ISSUE TITLE
fetch-jetty 404s

### ISSUE THREAD

**Issue by tomzeller** [iay/shibboleth-idp-docker#6]
Looks like Jetty downloads now refer to Maven Central rather than http://download.eclipse.org/jetty.

So, JETTY_RELDIR in fetch-jetty should be changed, but I'd rather point to the Shibboleth Nexus repository than Maven Central.

If you agree, I can submit a pull request.

**Comment by iay** [comment]
That would be helpful, please go ahead. Note that (if I recall correctly) this repository still assumes a 9.2 series Jetty. I do plan to rework it to use 9.3 and probably have its own jetty-base but that will probably be post-3.3.

**Comment by iay** [comment]
Patch applied and tested. Thanks again.
